version: '2.1'
services:
  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - NGINX_PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    volumes_from:
      - php-fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_COMPOSER_REPO_PACKAGIST=${PHP_COMPOSER_REPO_PACKAGIST}
    volumes:
      - ${WEB_DOCUMENT_PATH}:/var/www
    environment:
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS}
      - PHP_DEBUGGER=${PHP_DEBUGGER}

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: ${MYSQLD_FLAGS}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  redis:
    image: redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST} 
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mysql
