version: '2.1'
services:
  web:
    build:
      context: ./php-nginx
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_COMPOSER_REPO_PACKAGIST=${PHP_COMPOSER_REPO_PACKAGIST}
    volumes:
      - ${WEB_DOCUMENT_PATH}:/opt/www
      - ${NGINX_SITES_PATH}:/opt/nginx_sites
    environment:
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: ${MYSQLD_FLAGS}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always

  redis:
    image: redis
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mysql
    restart: always
